### ISSUE TITLE
dsBudget 2.0.25 issue: Internal Server Error

### ISSUE THREAD

**Issue by Starhunter999** [dsbudget/dsbudget#81]
Hi Soichi, 

As requested, below you'll find my server log. I hope it helps:

```
2017-01-31 20:22:50,797 ERROR http-127.0.0.1-16091-Processor7@78915122 org.apache.catalina.core.ContainerBase.[null].[localhost].[/dsbudget].[DivRepServlet] - Servlet.service() for servlet DivRepServlet threw exception
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
	at com.divrep.DivRep$Base64Writer.escapeAndWrite(DivRep.java:156)
	at com.divrep.DivRep$Base64Writer.write(DivRep.java:143)
	at java.io.PrintWriter.print(Unknown Source)
	at com.divrep.common.DivRepTextBox.render(DivRepTextBox.java:61)
	at com.divrep.DivRep.outputUpdatecode(DivRep.java:172)
	at com.divrep.DivRep.outputUpdatecode(DivRep.java:180)
	at com.divrep.DivRep.outputUpdatecode(DivRep.java:180)
	at com.divrep.DivRep.outputUpdatecode(DivRep.java:180)
	at com.divrep.DivRep.outputUpdatecode(DivRep.java:180)
	at com.divrep.DivRep.doRequest(DivRep.java:257)
	at com.divrep.DivRepServlet.doGet(DivRepServlet.java:66)
	at com.divrep.DivRepServlet.doPost(DivRepServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:873)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by soichih** [comment]
> java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64

This is exactly the error message I was seeing couple of weeks ago, and suddenly disappeared..

You've downloaded 2.0.25 from here, correct?
> https://github.com/dsbudget/dsbudget/releases

Can you run following command on your terminal (push Win+r key and enter "cmd")
> java -version

You should see "1.8.0_121".
```
C:\Users\Soichi Hayashi>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode, sharing)
```

If not, please go to https://java.com/ and download the latest version of Java (again..)

**Comment by Starhunter999** [comment]
Soichi,

Yes, I downloaded the installer from that website. As for the java version,
I get the same as you:

 java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode, sharing)

Starhunter


2017-02-01 5:17 GMT+01:00 Soichi Hayashi <notifications@github.com>:
